version: "3"

services:
  service1:
    image: vutruong1998/swarmtest:node
    ports:
      - 8085:8085
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure

  service2:
    image: vutruong1998/swarmtest:php
    ports:
      - 8086:8085
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure